"""empty message

Revision ID: 852ad5b3c8ac
Revises: 
Create Date: 2020-03-12 10:16:22.849906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852ad5b3c8ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('c_id', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('c_id'),
    sa.UniqueConstraint('c_name')
    )
    op.create_table('user',
    sa.Column('u_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sex', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('u_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('password')
    )
    op.create_table('videos',
    sa.Column('v_id', sa.Integer(), nullable=False),
    sa.Column('v_name', sa.Text(), nullable=False),
    sa.Column('cat_name', sa.Integer(), nullable=False),
    sa.Column('v_location', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cat_name'], ['category.c_name'], ),
    sa.PrimaryKeyConstraint('v_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
